runtime: python312
# Entrypoint will default to main.py and App Engine's magic.

instance_class: F1

handlers:
- url: /static
  static_dir: cgsite/static/
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

includes:
  - env_variables_prod.yaml